// react-old/src/components/Lenses.js
import React from 'react'
import Select from 'react-select';
import { connect } from 'react-redux';
import {Checkbox, CheckboxGroup} from 'react-checkbox-group';
import { mapStateToProps, mapDispatchToProps } from '../containers/ActivityList.js';


class Lenses extends React.Component {
  render() {
    return (
      <div className="row lenses"><div className="col-xs-10 col-xs-offset-1" style={{ textAlign: 'left' }}>
      <Select
        name="selected-actors"
        isMulti
        options={this.props.availableActors_select}
        placeholder="Lookup by Place/Project/Company - e.g. tmuxp, Social Amp, The Tao of tmux"
        onChange={this.props.onSelectedActorChange}
      />
      <Select
        name="selected-activity-types"
        isMulti
        options={this.props.activityTypes_select}
        placeholder="Filter by Activity Type(s) - e.g. Work, Open Source, Website, Volunteering"
        onChange={this.props.onSelectedActivityTypesChange}
      />
      <Select
        name="selected-languages"
        isMulti
        options={this.props.languages_select}
        filterOption={this.props.filterAvailableLanguages}
        value={this.props.selectedLanguages_select}
        placeholder="Filter by Programming Language(s) - e.g. Python, JavaScript, C++"
        onChange={this.props.onSelectedLanguageChange}
      />
      <CheckboxGroup name="selected-filters"
        value={this.props.selectedFilters}
        onChange={this.props.onSelectedFiltersChange}
        style={{ textAlign: 'center' }}
        className="row choices"
        checkboxDepth={3}
      >
         {Object.keys(this.props.filters).map(filterChoice => (
          <div className="col-sm" key={filterChoice}><div className="box">
            <Checkbox value={filterChoice} id={filterChoice} />
            <label htmlFor={filterChoice}>
              <span>{filterChoice}</span>
            </label>
          </div></div>
        ))}
      </CheckboxGroup>
    </div></div>
    );
  }
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Lenses);

// vue/src/components/Lenses.vue
<template>
  <div class="row lenses"><div class="col-xs-10 col-xs-offset-1">
    <multiselect
      :search="true"
      :multiple="true"
      placeholder="Lookup by Place/Project/Company - e.g. tmuxp, Social Amp, The Tao of tmux"
      label="name"
      track-by="name"
      id="actorFilter"
      :value="selectedActors"
      :options="availableActors"
      @input="updateSelectedActorsAction"
      >
      <template slot="option" slot-scope="props">
      <span>{{ props.option.name }}</span>
      <span class="tag">
      {{props.option.type}}
      </span>
      </template>
    </multiselect>

    <multiselect
      :search="true"
      :multiple="true"
      placeholder="Filter by Activity Type(s) - e.g. Work, Open Source, Website, Volunteering"
      id="activityFilter"
      track-by="component_name"
      :options="availableActivityTypes"
      :value="selectedActivityTypes"
      @input="updateSelectedActivityTypeAction"
      label="name"
     >
    </multiselect>

    <multiselect
      :search="true"
      :multiple="true"
      placeholder="Filter by Programming Language(s) - e.g. Python, JavaScript, C++"
      id="languageFilter"
      :options="availableLanguages"
      :value="selectedLanguages"
      track-by="name"
      label="name"
      @input="updateSelectedLanguagesAction"
     >
    </multiselect>

    <div class="row choices">
      <div v-for="fil in filters" :key="fil.id" class="roundedOne col-sm">
        <div class="box">
          <input type="checkbox" :id="fil" :value="fil" v-model="selectedFilters" >
          <label :for="fil">{{fil}}</label>
        </div>
      </div>
    </div>
  </div></div>
</template>

<script>
import Multiselect from 'vue-multiselect';
import { mapGetters, mapActions, mapState } from 'vuex';

export default {
  name: 'Lenses',
  components: { Multiselect },
  computed: {
    ...mapGetters([
      'actors',
      'availableActors',
      'availableActivityTypes',
      'availableLanguages',
    ]),
    ...mapState([
      'filters',
      'selectedActivityTypes',
      'selectedActors',
      'selectedLanguages',
    ]),
    ...{
      selectedFilters: {
        get() {
          return this.$store.state.selectedFilters;
        },
        set(value) {
          this.$store.commit('updateSelectedFilters', value);
        },
      },
    },
  },
  methods: {
    ...mapActions([
      'updateSelectedActivityTypeAction',
      'updateSelectedActorsAction',
      'updateSelectedFiltersAction',
      'updateSelectedLanguagesAction',
    ]),
  },
};
</script>

<style src="vue-multiselect/dist/vue-multiselect.min.css"></style>
